### ISSUE TITLE
Expansion Helicopter Keybind issue

### ISSUE THREAD

**Issue by Snoonose** [ysaroka/InediaInfectedAI#4]
Good Morning / Afternoon,

After installing your mod ive noticed the expansion helicopters are behaving very weird.

Expansion Version: Latest version
Expansion Mod(s): All expansion mods.
Reproducibility Rate: 100%, spawn a helicopter, get in it, default keybinds, not working (double checked keybinds in menu before attempting to fly)

Steps to Reproduce:
Get into helicopter > turn on helicopter > Hold default keybind of shift to take off nothing happens > Hold Z helicopter starts to take off > press W to tilt forwards nothing happens > press S to tilt backwards, start tilting forwards.

Expected Result:
Default keybinds (what appear in the keybind menu) should control the helicopter as intended

Actual Result:
Helicopter is un-controllable with seemingly random keys controlling different parts of the helicopter.

**Comment by ysaroka** [comment]
Strange, my mod does not affect these mechanics in any way.
Try wiping the server and checking again, maybe this is a conflict with context variables of some other mods that were used before.
If the problem persists, then when I have time I’ll see what’s wrong.

**Comment by Snoonose** [comment]
Still seem to have this issue, removing the mod fixes the issue.

Im not at my PC at the moment so i cant get you the crash log, script log or RTP files, but when i was looking i couldnt find any mentions to the helicopters or conflicts.

Sorry thats not super helpful haha

**Comment by ysaroka** [comment]
As I already wrote above - try to wipe server (delete `%DayZserverDir%\mpmissions\map.name\storage_1` directory) and reproduce the issue.
If the issue is reproduced, I will add it to todo list and download and install all these mods to understand what is going on.
You cannot be sure that disabling this mod affects the expansion mod until you wipe the server, since the context of user variables of other mods may conflict when enabling this mod.
Server wipe clears variable context.
Naturally, the wipe must be done on test server, as this will destroy all player data.

**Comment by ysaroka** [comment]
Or do you mean that you did wipe and the issue was reproduced?

**Comment by Snoonose** [comment]
Im unable to just delete all my player data on the live server haha, ill setup a test server and duplicate my modlist and attempt to replicate the issue on a fresh server.

I wont be able to do this for several hours as im still at work.

Thanks for getting back to me. When i get a chance ill do the above and post my findings here

**Comment by ysaroka** [comment]
Since there was no response from you for a very long time, I installed this server configuration, wiped the server and tested it:
"-mod=@CF;@VPPAdminTools;@Dabs Framework;@DayZ-Expansion-Core;@DayZ-Expansion-Licensed;@DayZ-Expansion-Animations;@DayZ-Expansion-Vehicles;@InediaInfectedAI;"
No problems were found with helicopter's control.

**Comment by Snoonose** [comment]
Hello,

Apologies for the delay i have been working a 60 hour work week and had 0 time to get on my pc.

Yeah i have just setup a fresh server and it seems to be working fine, which is very strange. perhaps it was the conflicting of context variables of some other mods.

Thankyou for your help and apologies for the run around. 
ill keep digging through my modlist adding them back into the test server until it breaks (if it does) the only other mod i could think of is Boomlays Things. but im no modder so i have no idea.

Cheers
