### ISSUE TITLE
Fixed bone name that caused server crash sometime

### ISSUE THREAD

**Issue by sysrover** [ysaroka/InediaInfectedAI#43]
Some of the creatures were based on zombies but used custom skeletons, but in your script, you used the fixed bone name 
m_InediaInfectedAI_headBoneIndex = GetBoneIndexByName("Head");
This causes a server crash if it cant find this bone.
Solution could be to add one more option to config or making check if this bone exist.

**Comment by ysaroka** [comment]
This should not cause a server crash because the vanilla proto function **DayZCreature.GetBoneIndexByName(...)** returns "-1" if the bone is not found.
And if the bone is not found, i.e., **m_InediaInfectedAI_headBoneIndex** = -1, then the logic for getting the coordinates of this bone in the **ZombieBase.InediaInfectedAI_GetHeadPosition()** method is not used, and this also cannot cause a server crash.

Therefore, it is not necessary to check for the existence of the bone, as the method **DayZCreature.GetBoneIndexByName(...)** already does this:
```
scripts\3_game\entities\dayzanimal.c:

...

class DayZCreature extends EntityAI
{
    ...
    
    //! returns bone index for a name (-1 if pBoneName doesn't exist)
    proto native int GetBoneIndexByName(string pBoneName);
    
    ...
}
```

**Comment by sysrover** [comment]
I found that this happens only in debug mode, somehow GetBoneIndexByName("Head"); gives me id 17 but in my skeleton I don't have this bone. Looks in debug mode dayz mix somehow bones. But on real server everything works. FOr now for debugging I will make small mod tu turn of your function and will continue testing.
Thanks for fast reply.
